chore(build): Add support for drift detection of generated code
cloudquery/cq-provider-github pull request #22
Opened 2022-08-08 09:31 UTC by hermanschaaf

This adds a new workflow that checks that generated code remains the same when go generate is run again. It currently needs to be specifically enabled by adding //check-for-changes to the top of the generator .hcl file.

2022-08-08 09:42 UTC, erezrokah requested changes
🔥 Same as 🚀  Same comment as https://github.com/cloudquery/cq-provider-gcp/pull/468#pullrequestreview-1064896387 regarding paths filters

2022-08-09 09:45 UTC, hermanschaaf commented on resources/services/teams/teams.go
> +						Type:        schema.TypeString,
@roneli I don't know whether this should be `TypeBigInt` or `TypeString` -- the generator generates String, so I went with that for now.

2022-08-09 09:45 UTC, hermanschaaf commented on resources/services/teams/teams.go
> +						Type:        schema.TypeString,
@roneli I don't know whether this should be `TypeBigInt` or `TypeString` -- the generator generates String, so I went with that for now.

2022-08-09 09:46 UTC, hermanschaaf commented on resources/services/teams/teams.go
> +						Type:        schema.TypeString,
Oh nevermind, the tests failed. Guess it should be TypeBigInt after all

2022-08-09 09:59 UTC, hermanschaaf commented
I have now also added the drift detection to all existing files and fixed any drift that had already occurred. To get the script to work also involved bringing the directory structure in line with other providers.

2022-08-09 10:10 UTC, erezrokah approved these changes

2022-08-09 11:50 UTC, roneli approved these changes
LGTM, one minor nit as we moved to packages feels maybe that billing/action_billing.go is redundant and we can do billing/actions etc' wdyt?

2022-08-09 12:07 UTC, hermanschaaf commented
@roneli I agree with you, however I think if we change the resource, that would also change the table name. Maybe let's do that in a separate PR if we're going to make a breaking change.

2022-08-09 12:09 UTC, merged